### PR TITLE
Add ability to use nested fields from relations

### PR DESCRIPTION
**Pull request by kibblerz**
### What does it do?

I adjusted how the paths are parsed to allow for the use of relation fields. So with this PR, you can use a related contenttypes fields in the path. 

This PR only supports 1 level of depth when using relations. If the relation returns an array, the first result will be used. Would like to improve this in the future

### Why is it needed?

Currently, relational attributes aren't able to be used.

### How to test it?
If the content type is called company, with relations to employees:
/company/[employee[name]]/[post]

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by boazpoolman** [comment]
Thanks @kibblerz,
I think this is a great feature.

Though it seems as if you have some kind of linting that applies on save that does not match up with the linting of this repo.

Could you check the issues that came out of the pipeline?
https://github.com/boazpoolman/strapi-plugin-sitemap/runs/5668992189?check_suite_focus=true

**Comment by kibblerz** [comment]
Sure thing!

**Review by boazpoolman — APPROVED** [review]

**Comment by kibblerz** [comment]
Thanks for approving! 
When do you think this could be published on npm?

**Comment by boazpoolman** [comment]
I still have to do a manual review of the new feature. Until then; you can allready use this PR in your project like this;

yarn add boazpoolman/strapi-plugin-sitemap#pull/75/head
npm install boazpoolman/strapi-plugin-sitemap#pull/75/head

**Review by boazpoolman — COMMENTED** [review]
Hey @kibblerz,

I've thouroughly reviewed your PR. Overall it looks great! Thanks for all the work.
I still have some questions & comment which I have mostly included in the code review.

There was still one question I had;
Did you also test this for a multilingual site?

**Comment by boazpoolman** [comment]
@kibblerz Thanks for the changes!

I've tested it and it works pretty much perfect.
Only some issues with a multilingual Strapi install.

For some reason the `localizations` attribute on a content type looks like this:

```
localizations: {
  writable: true,
  private: false,
  configurable: false,
  visible: false,
  type: 'relation',
  relation: 'oneToMany',
  target: 'api::page.page'
},
```
  
So the `target` is not actually the query string of the locale content type, but the query string of the current content type we're querying. So this is the oposite of how a "normal" relation works. We would expect target to be the query string of a locale content type.

Also, when we're creating a pattern for a content type with localizations enabled we see duplicate field options to add to the pattern. So duplicate entries are returned by the `getAllowedFields` service. See screenshot:

Schermafbeelding 2022-04-16 om 22 52 48

When that's finished I think we need to write some tests for the new pattern logic, but all in all this is a great new feature. Thanks for the work you have allready done on this!

Happy easter 🐣

**Comment by boazpoolman** [comment]
I've updated your PR to address the issues I mentioned above.
The change removes the possibility to add fields from the localizations relation in the URL pattern. I think that should be fine as the locale is really just there for internal use of the `@strapi/i18n-plugin` package.

Also I have written some tests for the relational pattern logic. Though whilst doing that I noticed there was one case I was a bit confused with when testing. Which was this part: https://github.com/boazpoolman/strapi-plugin-sitemap/pull/75/files#diff-f306920aa698f85f84aa8ebec6081fda2c285173603fd4dd8ef7e692566699ebR82

A relation field can be an array. So I guess that is for when there can be multiple relations. Like a one-to-many relation type. Though then we just use the first relation?
@kibblerz Could you elaborate on that.

**Comment by kibblerz** [comment]
@boazpoolman Yes it is set to use the first relation when the relation is an array. The only other solution i thought of was to create a different sitemap path for each relation. Do you have a better recommendation?

**Comment by boazpoolman** [comment]
I agree. It makes sense to have the pattern be like `/test/[relation[0].field]` to query the first relation.

If we don’t do that I think we should not allow to add relations to the pattern which are of type *-to-many. As you can’t accurately select the relation. Which is fine by me.

**Comment by boazpoolman** [comment]
@kibblerz I've made some changes and created an issue for Array relations #78.

Could you test it on your side to see if everything still works for you?

If so; I think we can merge this :)

**Comment by kibblerz** [comment]
Yes, everything's still working!

**Pull request merged**
