### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by pr0gr8mm3r**
All in the title.

Had to extract a string to translate it. There might be more, only looked for this for now.

### How to test it?

Create test env, set your language to german.

### CODE REVIEW

**Comment by boazpoolman** [comment]
This is great! Thank you.
Some text is still hardcoded.
Let me do some work to abstract all text into the translation files.

Can I afterwards ask you to check the translations once more? Then we can make sure everything is nicely translated 🙂

**Comment by pr0gr8mm3r** [comment]
Yeah, sure!

**Comment by boazpoolman** [comment]
How do I change the admin language to German?
In my profile I only get the options French and English:
Screenshot 2021-12-12 at 21 20 09

**Comment by pr0gr8mm3r** [comment]
Hm, maybe you have to enable the languages in `src/admin/app.js`:
```
 ​export​ ​default​ ​{ 
 ​    ​config​: ​{ 
 ​        ​locales​: ​[​'en', 'fr', 'de'​]​
     }
}
```

**Comment by boazpoolman** [comment]
That is it! Thanks

**Comment by boazpoolman** [comment]
Hey @pr0gr8mm3r,
I abstracted all translations strings into the `en.json` translation file.

Could you once more compare the `en.json` file to the `de.json` file and add/update the translations?

**Comment by pr0gr8mm3r** [comment]
I updated my translations

**Comment by boazpoolman** [comment]
Awesome!

**Pull request merged**
