### PR TITLE
fix: Fixed double forward slashes if relation field was empty

### PR DESCRIPTION
**Pull request by TriPSs**
### What does it do?

If the relation was empty you would end up with double forward slashes, this caused the url to not be valid in the sitemap.

### CODE REVIEW

**Comment by TriPSs** [comment]
@boazpoolman anything in this PR preventing it from being checked/merged?

**Comment by boazpoolman** [comment]
@TriPSs I've started a review which you haven't responded on yet.

The de-duplication of forward slashed is allready embeded in the code.
Also your implementation removes the slased completely, instead of de-duplicating them.
So I don't see a reason why this needs to be merged.

I've tested this out in a ideone. See https://ideone.com/m3coSi.
Not sure how long that ideone will be saved, so I've added a screenshot here as well:

Schermafbeelding 2022-09-05 om 12 06 27

**Comment by TriPSs** [comment]
I don't see any comments?

The deduplication does not work when the prefixed variable is empty, my fix makes sure that there are never more then 1 slash in front, I see it now also removes all slashes, it will check it as it should only remove them from the beginning.

In the code I have locally the pattern was something like this `/[category.slug]/[page.slug]`, the category is optional causing now the url to become `///page-slug`, the current code only removes one forward slash instead of two. See https://ideone.com/1juTNa for example

**Comment by boazpoolman** [comment]
Ah I see whats happening now. Thanks for explaining.
Though your code is also not completely valid as it will remove de slashed all together.

Probably just changing my original regex could do the job.
How about:

```
pattern = pattern.replace(/\/+/g, "/"); // Remove duplicate forward slashes.
pattern = pattern.startsWith('/') ? pattern : `/${pattern}`; // Make sure we only have on forward slash.
```

That will remove duplicate slashes regardless of it's position.

**Comment by TriPSs** [comment]
Sounds good! Will update the PR

**Comment by TriPSs** [comment]
@boazpoolman was this released already?

**Comment by boazpoolman** [comment]
It was not no. I've merged it into the beta branch and will release together with next beta release. No eta on that.

In the meantime you can install the PR in your project like so:

yarn add boazpoolman/strapi-plugin-sitemap#pull/94/head
npm install boazpoolman/strapi-plugin-sitemap#pull/94/head

**Comment by boazpoolman** [comment]
@TriPSs This was released on NPM as a beta release.
See [v2.1.0-beta.2](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/2.1.0-beta.2).

**Pull request merged**
